apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: map-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: map-service
    app.kubernetes.io/part-of: dc-metro-map
  name: map-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: map-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: map-service
    spec:
      containers:
      - image: quay.io/jduimovich0/dc-metro-map@sha256:63fd08ff107d4999cd195d6261f22f4c49d28c5794b1f715acb589c8348efb05
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
